exclude: ['grunt.js']
auto: true

title: 'Jake Harding'
author:
  name: 'Jake Harding'
  email: 'jacob.s.harding@gmail.com'
  twitter: 'JakeHarding'
  github: 'jharding'

JS_PATH: '/public/js'
CSS_PATH: '/public/style'
IMG_PATH: '/public/img'
